# dein_lazy.toml

# ======================================
# dark-power series

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_source = '''
  " Note: for profile
  "let g:denops#server#deno_args = [
  "    \ '-q',
  "    \ '--no-check',
  "    \ '--unstable',
  "    \ '-A',
  "    \ '--inspect',
  "    \ ]
'''

#[[plugins]]
#repo = 'BurntSushi/ripgrep'

# ======================================
# markdown

[[plugins]]
repo = 'junegunn/goyo.vim'
on_ft = 'md'
hook_add = '''
    autocmd! User GoyoEnter Limelight 0.7
    autocmd! User GoyoLeave Limelight!
'''

[[plugins]]
repo = 'junegunn/limelight.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md set filetype=markdown
    "let g:previm_open_cmd = 'Chrome'
    "let g:previm_open_cmd = 'Firefox'
    let g:previm_enable_realtime = 1
    let g:previm_open_cmd = 'C:\\Program\ Files\ (x86)\\Google\\Chrome\\Application\\chrome.exe'
    "let g:previm_wsl_mode = 1
    nnoremap <silent> <C-p> :PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    let g:netrw_nogx = 1 " disable netrw's gx mapping.
    nmap gx <Plug>(openbrowser-smart-search)
    vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_source = 'vim-markdown'
hook_add ='''
    function! s:isAtStartOfLine(mapping)
      let text_before_cursor = getline('.')[0 : col('.')-1]
      let mapping_pattern = '\V' . escape(a:mapping, '\')
      let comment_pattern = '\V' . escape(substitute(&l:commentstring, '%s.*$', '', ''), '\')
      return (text_before_cursor =~? '^' . ('\v(' . comment_pattern . '\v)?') . '\s*\v' . mapping_pattern . '\v$')
    endfunction
    
    inoreabbrev <expr> <bar><bar>
              \ <SID>isAtStartOfLine('\|\|') ?
              \ '<c-o>:TableModeEnable<cr><bar><space><bar><left><left>' : '<bar><bar>'
    inoreabbrev <expr> __
              \ <SID>isAtStartOfLine('__') ?
              \ '<c-o>:silent! TableModeDisable<cr>' : '__'
'''

# ======================================
# Vimwiki for Zettelkasten (LYT note-taking system)

[[plugins]]
repo = 'vimwiki/vimwiki'
#on_source = 'vim-markdown'
on_map = {n = '<Plug>'}
#on_cmd = 'VimwikiIndex'
hook_add = '''
    let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
    let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax':'markdown', 'ext':'.md'}]
    let g:vimwiki_use_mouse = 1
    let g:vimwiki_folding = 'expr'
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_markdown_link_ext = 1
    nmap ww <Plug>(vimwiki)
'''

[[plugins]]
repo = 'michal-h21/vim-zettel'
on_source = 'vimwiki'
hook_add = '''
    let g:zettel_format = '%title'
'''

# ======================================
# calendar

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
'''

