# dein_lazy.toml

# ======================================
# markdown

[[plugins]] #Distraction-free writing in Vim
repo = 'junegunn/goyo.vim'
on_ft = 'md'
hook_add = '''
    autocmd! User GoyoEnter Limelight 0.7
    autocmd! User GoyoLeave Limelight!
'''

[[plugins]] #Hyperfocus-writing in Vim
repo = 'junegunn/limelight.vim'

[[plugins]] #Distraction-free coding for Neovim
repo = 'folke/zen-mode.nvim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
hook_post_update = '''
    call mkdp#util#install()
'''
hook_add = '''
    nnoremap <silent> <C-p> :MarkdownPreview<CR>
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_source = 'vim-markdown'
hook_add ='''
    function! s:isAtStartOfLine(mapping)
      let text_before_cursor = getline('.')[0 : col('.')-1]
      let mapping_pattern = '\V' . escape(a:mapping, '\')
      let comment_pattern = '\V' . escape(substitute(&l:commentstring, '%s.*$', '', ''), '\')
      return (text_before_cursor =~? '^' . ('\v(' . comment_pattern . '\v)?') . '\s*\v' . mapping_pattern . '\v$')
    endfunction
    
    inoreabbrev <expr> <bar><bar>
              \ <SID>isAtStartOfLine('\|\|') ?
              \ '<c-o>:TableModeEnable<cr><bar><space><bar><left><left>' : '<bar><bar>'
    inoreabbrev <expr> __
              \ <SID>isAtStartOfLine('__') ?
              \ '<c-o>:silent! TableModeDisable<cr>' : '__'
'''

# ======================================
# Vimwiki for Zettelkasten (LYT note-taking system)

[[plugins]]
repo = 'vimwiki/vimwiki'
#on_source = 'vim-markdown'
on_map = {n = '<Plug>'}
#on_cmd = 'VimwikiIndex'
hook_add = '''
    let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
    let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax':'markdown', 'ext':'.md'}]
    let g:vimwiki_use_mouse = 1
    let g:vimwiki_folding = 'expr'
    let g:vimwiki_auto_chdir = 1
    let g:vimwiki_markdown_link_ext = 1
    nmap ww <Plug>(vimwiki)
'''

[[plugins]]
repo = 'michal-h21/vim-zettel'
on_source = 'vimwiki'
hook_add = '''
    let g:zettel_format = '%title'
'''

# ======================================
# calendar

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
'''

